export * from './AbpCacheApi';
import { AbpCacheApi }  from './AbpCacheApi';
export * from './AccountApi';
import { AccountApi }  from './AccountApi';
export * from './App_activityApi';
import { App_activityApi }  from './App_activityApi';
export * from './App_activityInvitationApi';
import { App_activityInvitationApi }  from './App_activityInvitationApi';
export * from './App_activityPlanApi';
import { App_activityPlanApi }  from './App_activityPlanApi';
export * from './App_activityPlanTimeSlotApi';
import { App_activityPlanTimeSlotApi }  from './App_activityPlanTimeSlotApi';
export * from './App_activityTemplateApi';
import { App_activityTemplateApi }  from './App_activityTemplateApi';
export * from './App_analysisApi';
import { App_analysisApi }  from './App_analysisApi';
export * from './App_chatRoomApi';
import { App_chatRoomApi }  from './App_chatRoomApi';
export * from './App_chatRoomMessageApi';
import { App_chatRoomMessageApi }  from './App_chatRoomMessageApi';
export * from './App_commentApi';
import { App_commentApi }  from './App_commentApi';
export * from './App_descriptionApi';
import { App_descriptionApi }  from './App_descriptionApi';
export * from './App_fileApi';
import { App_fileApi }  from './App_fileApi';
export * from './App_friendInvitationApi';
import { App_friendInvitationApi }  from './App_friendInvitationApi';
export * from './App_locationApi';
import { App_locationApi }  from './App_locationApi';
export * from './App_ratingApi';
import { App_ratingApi }  from './App_ratingApi';
export * from './App_replyApi';
import { App_replyApi }  from './App_replyApi';
export * from './App_sessionApi';
import { App_sessionApi }  from './App_sessionApi';
export * from './App_tagApi';
import { App_tagApi }  from './App_tagApi';
export * from './App_tenantApi';
import { App_tenantApi }  from './App_tenantApi';
export * from './App_trackApi';
import { App_trackApi }  from './App_trackApi';
export * from './App_userApi';
import { App_userApi }  from './App_userApi';
export * from './FileApi';
import { FileApi }  from './FileApi';
export const APIS = [AbpCacheApi, AccountApi, App_activityApi, App_activityInvitationApi, App_activityPlanApi, App_activityPlanTimeSlotApi, App_activityTemplateApi, App_analysisApi, App_chatRoomApi, App_chatRoomMessageApi, App_commentApi, App_descriptionApi, App_fileApi, App_friendInvitationApi, App_locationApi, App_ratingApi, App_replyApi, App_sessionApi, App_tagApi, App_tenantApi, App_trackApi, App_userApi, FileApi,];
