/**
 * ProjectIntelligence.WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface CreateSubmissionInput {
    parentFolderId?: string;

    fileIds?: Array<string>;

    expectedReplyDate?: Date;

    requestAction?: CreateSubmissionInput.RequestActionEnum;

    replyCompanyIds?: Array<string>;

}
export namespace CreateSubmissionInput {
    export enum RequestActionEnum {
        NUMBER_301 = <any> 301,
        NUMBER_302 = <any> 302,
        NUMBER_303 = <any> 303
    }
}
