/**
 * ProjectIntelligence.WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface CreateSubmissionReplyInput {
    submissionId?: string;

    fileIds?: Array<string>;

    expectedReplyDate?: Date;

    replyStatus?: CreateSubmissionReplyInput.ReplyStatusEnum;

}
export namespace CreateSubmissionReplyInput {
    export enum ReplyStatusEnum {
        NUMBER_201 = <any> 201,
        NUMBER_202 = <any> 202,
        NUMBER_203 = <any> 203,
        NUMBER_401 = <any> 401,
        NUMBER_402 = <any> 402
    }
}
