/**
 * ProjectIntelligence.WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface FileNotificationDto {
    file?: models.FileDto;

    fileAction?: FileNotificationDto.FileActionEnum;

    creator?: models.UserLightDto;

    creationTime?: Date;

    parentFolderName?: string;

    rootFolderName?: string;

    projectNotificationType?: FileNotificationDto.ProjectNotificationTypeEnum;

    id?: string;

}
export namespace FileNotificationDto {
    export enum FileActionEnum {
        NUMBER_10 = <any> 10,
        NUMBER_20 = <any> 20,
        NUMBER_30 = <any> 30
    }
    export enum ProjectNotificationTypeEnum {
        NUMBER_100 = <any> 100,
        NUMBER_200 = <any> 200,
        NUMBER_201 = <any> 201,
        NUMBER_202 = <any> 202
    }
}
