/**
 * ProjectIntelligence.WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface FolderNotificationDto {
    meetingFolder?: models.MeetingFolderLightDto;

    submissionFolder?: models.SubmissionFolderLightDto;

    folderAction?: FolderNotificationDto.FolderActionEnum;

    submissionStatus?: FolderNotificationDto.SubmissionStatusEnum;

    creator?: models.UserLightDto;

    creationTime?: Date;

    parentFolderName?: string;

    rootFolderName?: string;

    projectNotificationType?: FolderNotificationDto.ProjectNotificationTypeEnum;

    id?: string;

}
export namespace FolderNotificationDto {
    export enum FolderActionEnum {
        NUMBER_10 = <any> 10,
        NUMBER_20 = <any> 20,
        NUMBER_30 = <any> 30,
        NUMBER_110 = <any> 110,
        NUMBER_120 = <any> 120
    }
    export enum SubmissionStatusEnum {
        NUMBER_201 = <any> 201,
        NUMBER_202 = <any> 202,
        NUMBER_203 = <any> 203,
        NUMBER_301 = <any> 301,
        NUMBER_302 = <any> 302,
        NUMBER_303 = <any> 303,
        NUMBER_401 = <any> 401,
        NUMBER_402 = <any> 402
    }
    export enum ProjectNotificationTypeEnum {
        NUMBER_100 = <any> 100,
        NUMBER_200 = <any> 200,
        NUMBER_201 = <any> 201,
        NUMBER_202 = <any> 202
    }
}
