/**
 * ProjectIntelligence.WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface GetSubmissionFolderStatusPairOutput {
    pairs?: { [key: string]: number; };

}
export namespace GetSubmissionFolderStatusPairOutput {
    export enum PairsEnum {
        _0 = <any> '0',
        _200 = <any> '200',
        _300 = <any> '300',
        _400 = <any> '400'
    }
}
