/**
 * ProjectIntelligence.WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface SubmissionReplyDto {
    ownedCompany?: models.CompanyDto;

    files?: Array<models.SubmissionFileReplyDto>;

    overallStatus?: SubmissionReplyDto.OverallStatusEnum;

    expectedReplyDate?: Date;

    id?: string;

}
export namespace SubmissionReplyDto {
    export enum OverallStatusEnum {
        NUMBER_0 = <any> 0,
        NUMBER_200 = <any> 200,
        NUMBER_300 = <any> 300,
        NUMBER_400 = <any> 400
    }
}
